### PR TITLE
quotemeta the stuff intended literally in RE

### PR DESCRIPTION
**Pull request by mohawk2**
This is needed on 5.8.8 at least - see https://travis-ci.org/tsee/extutils-cppguess/jobs/513220203 if interested.

### CODE REVIEW

**Comment by Leont** [comment]
LGTM

**Comment by mohawk2** [comment]
This is also being tracked on https://rt.perl.org/Public/Bug/Display.html?id=133966

**Comment by mohawk2** [comment]
It's been applied to `blead`: https://perl5.git.perl.org/perl.git/commit/4f13e4588f9a08564a56a0d6db821f2803aed09f

**Comment by mohawk2** [comment]
This has been merged to `blead`, and released to CPAN, so closing.

@ambs How do we update this repo so it matches `blead`? Want me to attempt it, or is there a recognised way?

**Pull request closed without merging**
